version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
python:
  install:
    - method: pip
      path: .
    - requirements: docs/requirements-docs.txt  # if you have one
sphinx:
  configuration: docs/source/conf.py
formats:
  - html
  - pdf
  - epub