version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

jobs:
  pre_install:
    - python --version
    - python -m pip install poetry
    # Give Poetry the export command:
    - python -m poetry self add poetry-plugin-export
    # Now this will work:
    - python -m poetry export --format=requirements.txt --output=req-docs.txt --extras docs
  post_install:
    - pip install -r req-docs.txt
    - pip install -e .
    - pip install pyyaml
  pre_build:
    - python ./scripts/visualize-ga-workflow.py > ./docs/cicd_mermaid.md
    - python ./scripts/visualize-dockerfile.py > ./docs/dockerfile_mermaid.md

sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: false

formats:
  - pdf
  - epub

python:
  install:
    # this ensures RTD picks up your exported deps
    - requirements: req-docs.txt
