# .readthedocs.yml
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  jobs:
    # these run in order before RTD’s “install” step
    pre_install:
      - python --version
      - python -m pip install poetry
      - python -m poetry self add poetry-plugin-export
      - python -m poetry export \
          --format=requirements.txt \
          --output=req-docs.txt \
          --extras docs
    # this replaces RTD’s default “install” step for your code+deps
    post_install:
      - pip install -r req-docs.txt
      - pip install -e .
      - pip install pyyaml
    # run your custom scripts before the Sphinx build
    pre_build:
      - python ./scripts/visualize-ga-workflow.py \
          > ./docs/cicd_mermaid.md
      - python ./scripts/visualize-dockerfile.py \
          > ./docs/dockerfile_mermaid.md

python:
  install:
    # install your package itself
    - method: pip
      path: .
    # (Optional) additional pure‐pip requirements
    - requirements: req-docs.txt

sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: false

formats:
  - pdf
  - epub
