# .readthedocs.yml
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  jobs:
    pre_build:
      # Generate one .rst per module under docs/api
      - sphinx-apidoc --force --module-first --separate \
          -o docs/api \
          quma
      - python ./scripts/visualize-ga-workflow.py > docs/cicd_mermaid.md
      - python ./scripts/visualize-dockerfile.py > docs/dockerfile_mermaid.md
    pre_install:
      - python --version
      # 1️⃣ Install both Poetry and the export plugin via pip:
      - python -m pip install poetry poetry-plugin-export
      # 2️⃣ Run export with normal, space-separated flags (no backslashes):
      - python -m poetry export -f requirements.txt -o req-docs.txt -E docs

python:
  install:
    # install your package itself
    - method: pip
      path: .
    # (Optional) additional pure‐pip requirements
    - requirements: req-docs.txt

sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: false

formats:
  - pdf
  - epub
